"""Compute backends for local and HPC-scale workflows."""

from hsa.compute.bayesian_execution import (
    BayesianCPUPlan,
    plan_bayesian_cpu_execution,
)
from hsa.compute.benchmark import (
    BenchmarkRecord,
    append_benchmark_record,
    benchmark_timer,
    distributed_worker_peak_rss,
    make_benchmark_record,
    operation_memory_monitor,
    read_benchmark_records,
    scaling_table,
    wall_timer,
)
from hsa.compute.chunking import (
    estimate_raster_bytes,
    iter_point_batches,
    iter_sample_raster_stack_chunked,
    persist_if_dask,
    rechunk_raster,
    sample_raster_stack_batched,
    suggest_point_batch_size,
    suggest_xy_chunks,
)
from hsa.compute.config import (
    ExecutionConfig,
    close_execution,
    execution_context,
    resolve_execution,
)
from hsa.compute.dask import (
    configure_dask_memory,
    get_or_create_client,
    initialize_earth_engine_on_workers,
    make_local_dask_client,
    make_slurm_cluster,
    recommend_local_worker_count,
    run_on_workers,
    shutdown_default_client,
)
from hsa.compute.dynamic import sample_dynamic_covariates_tiled
from hsa.compute.io import (
    open_raster_stack_zarr,
    read_table_parquet,
    write_raster_stack_zarr,
    write_table_parquet,
)
from hsa.compute.partitioned import (
    PointPartition,
    SampledPointPartition,
    iter_sample_raster_stack_partitioned,
    sample_raster_stack_partitioned,
)
from hsa.compute.persistence import release_distributed
from hsa.compute.planning import (
    plan_raster_chunks,
    recommend_worker_count,
    recommend_worker_geometry,
    spatial_task_count,
    storage_chunk_shape,
    task_density,
)
from hsa.compute.prepared import PreparedDataset, prepare_rsf_dataset
from hsa.compute.profiles import (
    BENCHMARK_PROFILES,
    COOLMUC4_HARDWARE,
    COOLMUC4_POINT_112_2026_09,
    COOLMUC4_POLICY,
    COOLMUC4_RASTER_112_2026_08,
    BenchmarkProfile,
    HardwareTopology,
    SitePolicy,
    benchmark_profile_for,
)
from hsa.compute.provenance import (
    RunManifest,
    build_run_manifest,
    collect_slurm_accounting,
    finalize_run_manifest,
    selected_environment,
    software_versions,
    write_run_manifest,
)
from hsa.compute.raster import compare_sampling_engines, sample_raster_stack_chunked
from hsa.compute.sites import (
    COOLMUC4,
    ExecutionPlan,
    HPCSiteProfile,
    WorkerGeometry,
    coolmuc4_execution,
    coolmuc4_plan,
    get_site_profile,
)
from hsa.compute.slurm import (
    SlurmAllocation,
    SlurmJob,
    cancel_slurm_job,
    current_slurm_allocation,
    slurm_allocation_client,
    slurm_available,
    slurm_job_status,
    submit_slurm_job,
    wait_for_slurm_job,
)
from hsa.compute.spatial_sharding import SpatialPointShard, plan_spatial_point_shards
from hsa.compute.storage import plan_zarr_shards, zarr_storage_units
from hsa.compute.topology import (
    RuntimeTopology,
    TopologyValidation,
    collect_worker_topology,
    discover_runtime_topology,
    spread_physical_cpus_across_llc,
    validate_worker_topology,
)
from hsa.compute.workloads import (
    RasterWorkload,
    geometry_for_core_budget,
    parse_geometry,
    raster_workload_for_gib,
    raster_workloads,
    weak_raster_workloads,
)

__all__ = [
    "BENCHMARK_PROFILES",
    "BayesianCPUPlan",
    "BenchmarkProfile",
    "BenchmarkRecord",
    "COOLMUC4",
    "COOLMUC4_HARDWARE",
    "COOLMUC4_POINT_112_2026_09",
    "COOLMUC4_POLICY",
    "COOLMUC4_RASTER_112_2026_08",
    "ExecutionConfig",
    "ExecutionPlan",
    "HPCSiteProfile",
    "HardwareTopology",
    "PointPartition",
    "PreparedDataset",
    "RasterWorkload",
    "RunManifest",
    "RuntimeTopology",
    "SampledPointPartition",
    "SitePolicy",
    "SlurmAllocation",
    "SlurmJob",
    "SpatialPointShard",
    "TopologyValidation",
    "WorkerGeometry",
    "append_benchmark_record",
    "benchmark_profile_for",
    "benchmark_timer",
    "build_run_manifest",
    "cancel_slurm_job",
    "close_execution",
    "collect_slurm_accounting",
    "collect_worker_topology",
    "compare_sampling_engines",
    "configure_dask_memory",
    "coolmuc4_execution",
    "coolmuc4_plan",
    "current_slurm_allocation",
    "discover_runtime_topology",
    "distributed_worker_peak_rss",
    "estimate_raster_bytes",
    "execution_context",
    "finalize_run_manifest",
    "geometry_for_core_budget",
    "get_or_create_client",
    "get_site_profile",
    "initialize_earth_engine_on_workers",
    "iter_point_batches",
    "iter_sample_raster_stack_chunked",
    "iter_sample_raster_stack_partitioned",
    "make_benchmark_record",
    "make_local_dask_client",
    "make_slurm_cluster",
    "open_raster_stack_zarr",
    "operation_memory_monitor",
    "parse_geometry",
    "persist_if_dask",
    "plan_bayesian_cpu_execution",
    "plan_raster_chunks",
    "plan_spatial_point_shards",
    "plan_zarr_shards",
    "prepare_rsf_dataset",
    "raster_workload_for_gib",
    "raster_workloads",
    "read_benchmark_records",
    "read_table_parquet",
    "rechunk_raster",
    "recommend_local_worker_count",
    "recommend_worker_count",
    "recommend_worker_geometry",
    "release_distributed",
    "resolve_execution",
    "run_on_workers",
    "sample_dynamic_covariates_tiled",
    "sample_raster_stack_batched",
    "sample_raster_stack_chunked",
    "sample_raster_stack_partitioned",
    "scaling_table",
    "selected_environment",
    "shutdown_default_client",
    "slurm_allocation_client",
    "slurm_available",
    "slurm_job_status",
    "software_versions",
    "spatial_task_count",
    "spread_physical_cpus_across_llc",
    "storage_chunk_shape",
    "submit_slurm_job",
    "suggest_point_batch_size",
    "suggest_xy_chunks",
    "task_density",
    "validate_worker_topology",
    "wait_for_slurm_job",
    "wall_timer",
    "weak_raster_workloads",
    "write_raster_stack_zarr",
    "write_run_manifest",
    "write_table_parquet",
    "zarr_storage_units",
]
